"use client";

import React, { useState } from "react";
import { generateInvestmentPlan } from "@/app/actions";
import { type InvestmentPlanOutput } from "@/ai/flows/investment-plan-generator";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Loader2, AlertTriangle, Shield, TrendingUp, BarChart } from "lucide-react";
import { cn } from "@/lib/utils";
import { MotionDiv } from "./MotionDiv";

type RiskProfile = "conservative" | "moderate" | "aggressive";

export default function InvestmentPlans() {
  const [loadingProfile, setLoadingProfile] = useState<RiskProfile | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<InvestmentPlanOutput | null>(null);
  const [selectedProfile, setSelectedProfile] = useState<RiskProfile | null>(null);

  const handlePlanRequest = async (riskProfile: RiskProfile) => {
    setLoadingProfile(riskProfile);
    setError(null);
    setResult(null);
    setSelectedProfile(riskProfile);

    const response = await generateInvestmentPlan({ riskProfile });

    if (response.error) {
      setError(response.error);
    } else if (response.data) {
      setResult(response.data);
    }

    setLoadingProfile(null);
  };
  
  const riskProfiles: { name: RiskProfile; label: string; icon: React.ReactNode; description: string }[] = [
    { name: 'conservative', label: 'Conservative', icon: <Shield className="h-6 w-6" />, description: "Focus on capital preservation with low-risk investments." },
    { name: 'moderate', label: 'Moderate', icon: <BarChart className="h-6 w-6" />, description: "A balanced approach seeking steady growth with manageable risk." },
    { name: 'aggressive', label: 'Aggressive', icon: <TrendingUp className="h-6 w-6" />, description: "Aim for higher returns by taking on greater market risk." },
  ];

  return (
    <Card className="shadow-lg border-border overflow-hidden">
      <CardHeader>
        <CardTitle className="font-headline text-2xl">Investment Starter Plans</CardTitle>
        <CardDescription>Choose a risk profile to see a sample investment plan generated by our AI.</CardDescription>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-1 gap-4">
          {riskProfiles.map(({name, label, icon, description}) => (
             <button
                key={name}
                className={cn(
                    "flex w-full items-center gap-4 rounded-lg border-2 bg-card p-4 text-left transition-all hover:border-primary",
                    "disabled:pointer-events-none disabled:opacity-50",
                    selectedProfile === name && "border-primary ring-2 ring-primary"
                )}
                onClick={() => handlePlanRequest(name)}
                disabled={!!loadingProfile}
              >
                {loadingProfile === name ? <Loader2 className="h-6 w-6 animate-spin text-primary"/> : React.cloneElement(icon as React.ReactElement, { className: "h-6 w-6 text-primary" })}
                <div className="flex-grow">
                    <p className="font-semibold text-card-foreground">{label}</p>
                    <p className="text-sm text-muted-foreground">{description}</p>
                </div>
                <div className="h-5 w-5 rounded-full border-2 border-primary flex items-center justify-center flex-shrink-0">
                    {selectedProfile === name && <div className="h-2.5 w-2.5 rounded-full bg-primary" />}
                </div>
              </button>
          ))}
        </div>
      </CardContent>

      {error && (
        <CardFooter className="flex-col items-start gap-2 rounded-none border-t bg-destructive/10 p-4">
          <div className="flex items-center gap-2">
            <AlertTriangle className="h-5 w-5 text-destructive" />
            <p className="text-destructive font-semibold">An error occurred</p>
          </div>
          <p className="text-destructive/80 text-sm">{error}</p>
        </CardFooter>
      )}

      {result && (
        <MotionDiv
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <CardFooter className="flex-col items-start gap-4 rounded-none border-t bg-muted/30 p-6">
              <h3 className="font-headline text-xl font-semibold capitalize text-foreground">{selectedProfile} Investment Plan</h3>
              <div className="text-base text-foreground/90 whitespace-pre-wrap leading-relaxed">
                  {result.plan}
              </div>
              <div className="mt-4 w-full rounded-lg border border-dashed border-amber-500 bg-amber-500/10 p-4 text-sm text-amber-700 dark:text-amber-300 dark:bg-amber-900/20 dark:border-amber-500/50">
                  <p className="font-semibold">Disclaimer</p>
                  <p>This is a sample plan. For personalized advice, use the 'Personalized Guidance' tool or consult a financial advisor.</p>
              </div>
          </CardFooter>
        </MotionDiv>
      )}
    </Card>
  );
}
